"""empty message

Revision ID: e0df458df43e
Revises: 224b9c215b54
Create Date: 2020-03-11 13:26:56.907689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0df458df43e'
down_revision = '224b9c215b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todos SET completed =  False WHERE completed IS NULL;')
    op.alter_column('todos','completed',nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
